# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-08 12:37
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, verbose_name='轮播名称')),
                ('images', models.ImageField(default='', upload_to='banner/%Y/%m', verbose_name='轮播图片')),
                ('index', models.IntegerField(default=100, verbose_name='顺序')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='新增时间')),
            ],
            options={
                'verbose_name': '首页轮播',
                'verbose_name_plural': '首页轮播',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='伙伴名称')),
                ('logo', models.ImageField(default='', upload_to='partner/%Y/%m', verbose_name='品牌LOGO')),
                ('index', models.IntegerField(default=100, verbose_name='顺序')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='新增时间')),
            ],
            options={
                'verbose_name': '合作伙伴',
                'verbose_name_plural': '合作伙伴',
            },
        ),
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(default='', max_length=50, verbose_name='岗位名称')),
                ('detail', DjangoUeditor.models.UEditorField(max_length='', verbose_name='岗位描述')),
                ('index', models.IntegerField(default=100, verbose_name='顺序')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='新增时间')),
            ],
            options={
                'verbose_name': '岗位招聘',
                'verbose_name_plural': '岗位招聘',
            },
        ),
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='企业名称')),
                ('address', models.CharField(default='', max_length=100, verbose_name='企业地址')),
                ('en_address', models.CharField(default='', max_length=100, verbose_name='英文企业地址')),
                ('tel', models.CharField(default='', max_length=50, verbose_name='企业电话')),
                ('email', models.CharField(default='', max_length=50, verbose_name='企业邮箱')),
                ('detail', DjangoUeditor.models.UEditorField(max_length='', verbose_name='企业描述')),
                ('en_detail', DjangoUeditor.models.UEditorField(max_length='', verbose_name='英文企业描述')),
            ],
            options={
                'verbose_name': '企业信息',
                'verbose_name_plural': '企业信息',
            },
        ),
    ]
